name = "jc-voxnos"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "58a6ac9954ea44d2972ba2cb9e1e077e"

[vars]
TTS_MODE = "google"

[[d1_databases]]
binding = "DB"
database_name = "jc-voxnos-surveys"
database_id = "131ed879-edf4-414c-83c7-c76fa5ede37c"

[[services]]
binding = "COGNOS"
service = "jc-cognos"
