name = "jc-voxnos"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "58a6ac9954ea44d2972ba2cb9e1e077e"

[vars]
TTS_MODE = "google"
