name = "voxnos"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "58a6ac9954ea44d2972ba2cb9e1e077e"

[vars]
TTS_MODE = "google"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "b347675bf9e34815b9c823a917eace29"

[[d1_databases]]
binding = "DB"
database_name = "voxnos"
database_id = "0998cfff-5efd-4b08-9186-4a3d4f528e98"

[[services]]
binding = "COGNOS"
service = "cognos"
